server:
  port:
    8080
  context-path:
    /meli
spring:
  data:
    mongodb:
      uri: "mongodb://localhost/meli-galaxy"
      database: meli-galaxy
galaxy:
  planets:
    - name: vulcano
      distanceFromSun: 1000
      angularRate: 5
      clockwise: false
    - name: ferengi
      distanceFromSun: 500
      angularRate: 1
      clockwise: true
    - name: betasoide
      distanceFromSun: 2000
      angularRate: 3
      clockwise: true